### PR TITLE
add maven and gradle code samples

### PR DESCRIPTION
**Pull request by navierula**

### CODE REVIEW

**Review by davidstanke — APPROVED** [review]
LG! I have just one suggestion, which I recommend you do in a separate PR after merging this one...

We can make it so users can do the Maven build locally, without having to install Maven to their system:

1. in the "maven-example" directory, run `mvn -N io.takari:maven:wrapper`
2. this will create a `.mvn` directory; `git add` and `commit` this
3. now, when people clone the repo, they can run Maven commands locally with `./mvnw <command>` (without needing to have maven on their system)

I ran the builds locally and in Cloud Build and everything worked. :)

**Comment by navierula** [comment]
@davidstanke, thanks for your review and for running these builds. After merging this PR, I'll follow those steps. @loosebazooka, I'm curious if something similar can be done for gradle?

A general question - should I mention in the README for these repos that [start.spring.io](https://start.spring.io/) was used to generate them?

**Comment by davidstanke** [comment]
Heya! For Gradle, it shouldn't be necessary (or it was already done?) -- I
was able to run ./gradlew without having Gradle installed locally.

As for mentioning start.spring.io in the README: IMHO, not necessary but
also nothing wrong with doing so.

**Comment by loosebazooka** [comment]
Oh sorry I missed this. Look good to me.

**Review by loosebazooka — APPROVED** [review]

**Pull request merged**
